<?php $this->title = 'Stránka nebyla nenalezena' ?>
<div id="err_message" style="background:white;border:1px solid #aaa;margin:100px auto;padding:20px;width:75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">Stránka neexistuje</h1>

<p style="margin:15px 0;">Omlouváme se Vám, ale Vámi požadovaná stránka nebyla na serveru nelazena.</p>
<p style="margin:15px 0;">Při Vašem požadavku mohly nastat následující problémy:
<ul>
	<li>Stránka na serveru neexistuje</li>
	<li>Stránka byla přesunuta</li>
	<li>Při zobrazování stránky nastala interní chyba</li>
	<li>Nenabízíme vámi požadovanou službu</li>
</ul>
</p>

<p style="margin:15px 0;">Pro novou navigaci pokračujte na <?= $this->link('úvodní stránku', $baseUrl) ?>.</p>

</div>