<?php $this->title = 'Nastala interní chyba' ?>
<div id="err_message" style="background:white;border:1px solid #aaa;margin:100px auto;padding:20px;width:75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">Nastala interní chyba</h1>

<p style="margin:15px 0;">Omlouváme se Vám, ale Vámi požadovaná stránka není k dispozici.</p>
<p style="margin:15px 0;">Při Vašem požadavku nastala na serveru interní chyba.
<ul>
	<li>Chvíli počkejte a pak zkuste akci zopakovat</li>
	<li>Pokud chyba přetrvává, kontaktujte prosím autora.</li>
</ul>
</p>

</div>