<?php $this->title = 'Nenalezena metoda | Hlen framework' ?>
<div id="err_message">

<h1>CHYBA: Nenalezena metoda</h1>
<p>Zkontrolujte URL (<em>router.php</em>), zda-li jste napsali správně název metody controlleru.</p>
<p>Pro vytvoření metody využijte následující kostru:</p>

<pre>
public function <?=HRouter::$action?>Action() {
	// váš kód
}
</pre>
<p>Po vypnutí ladícího režimu bude tato chyba nahrazenou E404.</p>

</div>