<?php $this->title = 'Neproběhl routing | Hlen framework' ?>
<div id="err_message" style="border: 1px solid #aaa;margin: 100px auto;padding: 20px;width: 75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">CHYBA: Nebyl proveden routing</h1>
<p style="margin: 15px 0;">Zkontrolujte, zda-li jste napsali správně url adresu.</p>
<p style="margin: 15px 0;">Pokud ano, zřejmě jste zatím nevytvořili správná pravidla pro routing. Využijte k tomu soubor <em>/app/config/router.php</em></p>
<p style="margin: 15px 0;">Po vypnutí ladícího režimu bude tato chyba nahrazenou E404.</p>

</div>