<?php $this->title = 'Chyba databáze | Hlen framework' ?>
<div id="err_message" style="border: 1px solid #aaa;margin: 100px auto;padding: 20px;width: 75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">CHYBA databáze</h1>

<p style="margin: 15px 0;">DIBI knihovna vyhodila následující výjimku:</p>

<pre><?=$exception->getMessage()?></pre>

<p style="margin: 15px 0;">Po vypnutí ladícího režimu bude tato chyba nahrazenou E404.</p>

</div>