<?php $this->title = 'Nenalezen view | Hlen framework' ?>
<div id="err_message" style="background:white;border:1px solid #aaa;margin:100px auto;padding:20px;width:75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">CHYBA: Nenalezen soubor view</h1>
<p style="margin: 15px 0;">Zkontrolujte, zda-li jste vytvořili soubor view:
<em><?= $missingView ?></em>
</p>

<p style="margin: 15px 0;">Po vypnutí ladícího režimu bude tato chyba nahrazenou E404.</p>

</div>