<?php $this->title = 'Nenalezen controller | Hlen framework' ?>
<div id="err_message">

<h1>CHYBA: Nenalezena třída controlleru</h1>
<p>Zkontrolujte URL (<em>router.php</em>), zda-li jste napsali správně název třídy controlleru.</p>
<p>Pro soubor s controllerem využijte následující kostru:

<pre>
class <?= HBasics::camelize(HRouter::$controller) ?>Controller extends Controller
{
    public function indexAction() {
        // váš kód
    }
}
</pre>
</p>

<p>Po vypnutí ladícího režimu bude tato chyba nahrazenou E404.</p>

</div>