<?php $this->title = 'Nenalezen controller | Hlen framework' ?>
<div id="err_message" style="border: 1px solid #aaa;margin: 100px auto;padding: 20px;width: 75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">CHYBA: Nenalezena třída controlleru</h1>
<p style="margin: 15px 0;">Zkontrolujte URL (<em>router.php</em>), zda-li jste napsali správně název třídy controlleru.</p>
<p style="margin: 15px 0;">Pro soubor s controllerem využijte následující kostru:

<pre>
class <?= HBasics::camelize(HRouter::$controller) ?>Controller extends Controller
{
    public function indexAction() {
        // váš kód
    }
}
</pre>
</p>

<p style="margin: 15px 0;">Po vypnutí ladícího režimu bude tato chyba nahrazenou E404.</p>

</div>